// Authentification

export const AUTH_LOGIN_PROCESS = 'AUTH_LOGIN_PROCESS';
export const AUTH_PROCESS = 'AUTH_PROCESS';
export const AUTH_LOGOUT_PROCESS = 'AUTH_LOGOUT_PROCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';

export const SET_AUTHENTICATE_REDIRECT_PATH = 'SET_AUTHENTICATE_REDIRECT_PATH';

// export const SET_ACCESS_ROLE_MODULE = 'SET_ACCESS_ROLE_MODULE';

// Role Module Permissions 
export const READ_ACCESS = 'READ_ACCESS';
export const GRANTED_ACCESS = 'GRANTED_ACCESS';
export const DENIED_ACCESS = 'DENIED_ACCESS';

// Application Setup
export const READ_APPLICATION_SETUP_FAILURE = 'READ_APPLICATION_SETUP_FAILURE';
export const READ_APPLICATION_SETUP = 'READ_APPLICATION_SETUP';
export const ADD_APPLICATION_SETUP = 'ADD_APPLICATION_SETUP';
