export const AUTHENTICATION_PROCESS = 'AUTHENTICATION_PROCESS';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

export const SET_AUTHENTICATE_REDIRECT_PATH = 'SET_AUTHENTICATE_REDIRECT_PATH';

// export const SET_ACCESS_ROLE_MODULE = 'SET_ACCESS_ROLE_MODULE';
